### ISSUE TITLE
Optional API Authentication

### ISSUE THREAD

**Issue by leandroalbero** [runpod-workers/worker-faster_whisper#18]
Something like bearer token, set by an environment variable on runpod.

**Comment by justinmerrell** [comment]
Where would this come into play?

**Comment by leandroalbero** [comment]
Correct me if I'm wrong, but without authentication anyone with the ip address can use my endpoint (?)

**Comment by justinmerrell** [comment]
You currently need to use your API key to make requests to your endpoint already :)
